version: '3.8'

services:
  # Main GraphRAG Pipeline
  graphrag-pipeline:
    build: .
    container_name: graphrag-pipeline
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GRAPHRAG_API_KEY=${GRAPHRAG_API_KEY}
      - OPENAI_API_KEY=${GRAPHRAG_API_KEY}
    volumes:
      - ./input:/app/input:ro  # Mount your PDF directory here
      - graphrag_output:/app/graphrag_output  # Persist output
    depends_on:
      - stirling-pdf
    networks:
      - graphrag-network
    stdin_open: true
    tty: true

  # Stirling PDF Service  
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf-service
    ports:
      - "8080:8080"
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
    volumes:
      - stirling_data:/usr/share/tessdata
    networks:
      - graphrag-network
    restart: unless-stopped

volumes:
  graphrag_output:
  stirling_data:

networks:
  graphrag-network:
    driver: bridge
