# Fast GraphRAG Settings Template
# Optimized for speed while maintaining reasonable quality
# 
# RATE LIMIT ANALYSIS for Groq API:
# - Groq TPM Limit: 250,000 tokens per minute
# - GPT-OSS 120B model with reasoning_effort: medium
# - Typical token usage per request: 2000-4000 tokens
# - Max safe concurrent requests: 3-5 (to stay under TPM limit)
# - Previous settings were too aggressive (20 concurrent) causing 429 errors
#
# CONCURRENCY STRATEGY:
# - Chat model concurrent_requests: 3 (conservative for GPT-OSS)
# - Embedding concurrent_requests: 8 (embeddings use fewer tokens)
# - num_threads: 8 (down from 50)
# - stagger: 0.3s (increased from 0.1s to space out requests)
# - global_search concurrency: 2 (most critical bottleneck)

encoding_model: cl100k_base
skip_workflows: []

# Model configurations - REQUIRED
models:
  default_chat_model:
    api_key: ${GROQ_API_KEY}
    type: openai_chat
    model: openai/gpt-oss-120b  # Groq-hosted GPT-OSS 120B - MUCH faster
    encoding_model: cl100k_base  # Explicitly specify tokenizer
    model_supports_json: true
    max_tokens: 4000
    temperature: 0
    top_p: 1
    n: 1
    request_timeout: 90.0  # Increased timeout for rate limit delays
    api_base: https://api.groq.com/openai/v1  # Groq API endpoint
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 10  # Reduced for Groq TPM limits (250k/min)
    max_retries: 5  # Increased retries for rate limit handling
    # Groq-specific parameters for GPT-OSS
    reasoning_effort: low  # low/medium/high for GPT-OSS reasoning

  default_embedding_model:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding
    model: text-embedding-3-small  # Fast and good quality
    max_tokens: 8191
    request_timeout: 30.0
    api_base: null
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 15  # Reduced for embeddings
    max_retries: 3

# Legacy LLM config (kept for compatibility)
llm:
  api_key: ${GROQ_API_KEY}
  type: openai_chat
  model: openai/gpt-oss-120b  # Groq-hosted GPT-OSS 120B
  encoding_model: cl100k_base  # Explicitly specify tokenizer
  model_supports_json: true
  max_tokens: 4000
  temperature: 0
  top_p: 1
  n: 1
  request_timeout: 90.0  # Increased for rate limit delays
  api_base: https://api.groq.com/openai/v1  # Groq API endpoint
  api_version: null
  organization: null
  proxy: null
  concurrent_requests: 10  # Reduced for Groq TPM limits

parallelization:
  stagger: 0.1  # Increased stagger to space out requests
  num_threads: 20  # Reduced for Groq rate limits

async_mode: threaded

embeddings:
  async_mode: threaded
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding
    model: text-embedding-3-small  # Fast and good quality
    max_tokens: 8191
    request_timeout: 30.0
    api_base: null
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 15  # Reduced for embeddings rate limits
    max_retries: 3

chunks:
  size: 1200  # Increased to reduce total API calls
  overlap: 50  # Reduced overlap for speed
  group_by_columns: [id]

input:
  type: file
  file_type: text
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt"

cache:
  type: none  # Disable caching to avoid service_tier validation errors

storage:
  type: file
  base_dir: "output/artifacts"

reporting:
  type: file
  base_dir: "output/reports"

entity_extraction:
  llm:
    api_key: ${GROQ_API_KEY}
    type: openai_chat
    model: openai/gpt-oss-120b  # Groq-hosted GPT-OSS 120B
    encoding_model: cl100k_base  # Explicitly specify tokenizer
    max_tokens: 2000  # Reduced tokens
    temperature: 0
    top_p: 1
    n: 1
    request_timeout: 90.0  # Increased timeout for rate limit delays
    api_base: https://api.groq.com/openai/v1  # Groq API endpoint
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 10  # Reduced for Groq TPM limits
    max_retries: 5  # Increased retries for rate limit handling
    reasoning_effort: low  # GPT-OSS reasoning level
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1  # Reduced for speed

summarize_descriptions:
  llm:
    api_key: ${GROQ_API_KEY}
    type: openai_chat
    model: openai/gpt-oss-120b
    encoding_model: cl100k_base  # Explicitly specify tokenizer
    max_tokens: 1500  # Reduced tokens
    temperature: 0
    top_p: 1
    n: 1
    request_timeout: 90.0  # Increased timeout for rate limit delays
    api_base: https://api.groq.com/openai/v1  # Groq API endpoint
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 10  # Reduced for Groq TPM limits
    max_retries: 5  # Increased retries for rate limit handling
    reasoning_effort: low  # GPT-OSS reasoning level
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  llm:
    api_key: ${GROQ_API_KEY}
    type: openai_chat
    model: openai/gpt-oss-120b
    encoding_model: cl100k_base  # Explicitly specify tokenizer
    max_tokens: 1500
    temperature: 0
    top_p: 1
    n: 1
    request_timeout: 90.0  # Increased timeout for rate limit delays
    api_base: https://api.groq.com/openai/v1  # Groq API endpoint
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 10  # Reduced for Groq TPM limits
    max_retries: 5  # Increased retries for rate limit handling
    reasoning_effort: low  # GPT-OSS reasoning level
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1  # Reduced for speed

community_reports:
  llm:
    api_key: ${GROQ_API_KEY}
    type: openai_chat
    model: openai/gpt-oss-120b
    encoding_model: cl100k_base  # Explicitly specify tokenizer
    max_tokens: 2000  # Reduced tokens
    temperature: 0
    top_p: 1
    n: 1
    request_timeout: 90.0  # Increased timeout for rate limit delays
    api_base: https://api.groq.com/openai/v1  # Groq API endpoint
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 10  # Reduced for Groq TPM limits
    max_retries: 5  # Increased retries for rate limit handling
    reasoning_effort: low  # GPT-OSS reasoning level
  prompt: "prompts/community_report.txt"
  max_length: 1000  # Reduced length
  max_input_length: 8000  # Reduced input

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false  # Disable for speed

umap:
  enabled: false  # Disable for speed

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:
  text_unit_prop: 0.5
  community_prop: 0.1
  conversation_history_max_turns: 5
  top_k_mapped_entities: 10
  top_k_relationships: 10
  max_tokens: 8000

global_search:
  max_tokens: 8000
  data_max_tokens: 8000
  map_max_tokens: 1000
  reduce_max_tokens: 2000
  concurrency: 2  # Reduced to avoid rate limits
  