# Fast GraphRAG Settings Template

encoding_model: cl100k_base
skip_workflows: []

models:
  default_chat_model:
    api_key: ${GROQ_API_KEY}
    type: openai_chat
    model: openai/gpt-oss-120b  
    encoding_model: cl100k_base  
    model_supports_json: true
    max_tokens: 4000
    temperature: 0
    top_p: 1
    n: 1
    request_timeout: 90.0  
    api_base: https://api.groq.com/openai/v1 
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 10  
    max_retries: 5  
    reasoning_effort: low  # low/medium/high for GPT-OSS reasoning

  default_embedding_model:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding
    model: text-embedding-3-small  
    max_tokens: 8191
    request_timeout: 30.0
    api_base: null
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 15  
    max_retries: 3

# Legacy LLM config (kept for compatibility)
llm:
  api_key: ${GROQ_API_KEY}
  type: openai_chat
  model: openai/gpt-oss-120b  
  encoding_model: cl100k_base  
  model_supports_json: true
  max_tokens: 4000
  temperature: 0
  top_p: 1
  n: 1
  request_timeout: 90.0  
  api_base: https://api.groq.com/openai/v1  
  api_version: null
  organization: null
  proxy: null
  concurrent_requests: 10  

parallelization:
  stagger: 0.1  
  num_threads: 20  

async_mode: threaded

embeddings:
  async_mode: threaded
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding
    model: text-embedding-3-small  
    max_tokens: 8191
    request_timeout: 30.0
    api_base: null
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 15  
    max_retries: 3

chunks:
  size: 3200  # changed between 800 to 3200 here
  overlap: 50  
  group_by_columns: [id]

input:
  type: file
  file_type: text
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt"

cache:
  type: none  

storage:
  type: file
  base_dir: "output/artifacts"

reporting:
  type: file
  base_dir: "output/reports"

entity_extraction:
  llm:
    api_key: ${GROQ_API_KEY}
    type: openai_chat
    model: openai/gpt-oss-120b  
    encoding_model: cl100k_base  
    max_tokens: 1200 
    temperature: 0
    top_p: 1
    n: 1
    request_timeout: 90.0  
    api_base: https://api.groq.com/openai/v1  
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 12
    max_retries: 5
    reasoning_effort: low
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,technology]  
  max_gleanings: 1  

summarize_descriptions:
  llm:
    api_key: ${GROQ_API_KEY}
    type: openai_chat
    model: openai/gpt-oss-120b
    encoding_model: cl100k_base  
    max_tokens: 1500  
    temperature: 0
    top_p: 1
    n: 1
    request_timeout: 90.0  
    api_base: https://api.groq.com/openai/v1  
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 10
    max_retries: 5
    reasoning_effort: low
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  llm:
    api_key: ${GROQ_API_KEY}
    type: openai_chat
    model: openai/gpt-oss-120b
    encoding_model: cl100k_base  
    max_tokens: 1500
    temperature: 0
    top_p: 1
    n: 1
    request_timeout: 90.0  
    api_base: https://api.groq.com/openai/v1  
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 10  
    max_retries: 5 
    reasoning_effort: low  
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1  

community_reports:
  llm:
    api_key: ${GROQ_API_KEY}
    type: openai_chat
    model: openai/gpt-oss-120b
    encoding_model: cl100k_base 
    max_tokens: 2000 
    temperature: 0
    top_p: 1
    n: 1
    request_timeout: 90.0  
    api_base: https://api.groq.com/openai/v1  
    api_version: null
    organization: null
    proxy: null
    concurrent_requests: 10  
    max_retries: 5  
    reasoning_effort: low 
  prompt: "prompts/community_report.txt"
  max_length: 1000  
  max_input_length: 8000  

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false 

umap:
  enabled: false  

snapshots:
  graphml: true  # Enable graph visualization export
  raw_entities: false
  top_level_nodes: false

local_search:
  text_unit_prop: 0.5
  community_prop: 0.1
  conversation_history_max_turns: 5
  top_k_mapped_entities: 10
  top_k_relationships: 10
  max_tokens: 8000

global_search:
  max_tokens: 8000
  data_max_tokens: 8000
  map_max_tokens: 1000
  reduce_max_tokens: 2000
  concurrency: 2  
