services:
  stirling-pdf-service:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf-demo
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - stirling_data:/usr/share/tessdata
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
    networks:
      - graphrag-network

  graphrag-pipeline:
    build:
      context: ..
      dockerfile: demo/Dockerfile.demo
    container_name: graphrag-demo
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - stirling-pdf-service
    volumes:
      - ../input:/app/input
      - graphrag_output:/app/graphrag_output
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GRAPHRAG_API_KEY=${OPENAI_API_KEY}
    networks:
      - graphrag-network

volumes:
  stirling_data:
    name: demo_stirling_data
  graphrag_output:
    name: demo_graphrag_output

networks:
  graphrag-network:
    name: demo-network
